apiVersion: v1
kind: Service
metadata:
  Labels:
      app: solar-system
    name: solar-system
    namespace: _{_NAMESPACE_}_
spec:
  selector:
    app: solar-system
  ports:
    - port: 3000
      targetPort: 3000
  externalTrafficPolicy: Local
  type: LoadBalancer